name: 'Build IBM HA PAR offering release'
on:
    push:
        tags:
        - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'Make the Distribution Directory'
              run: |
                  mkdir  ibm-fortigate-cross-zone-ha-par-terraform-deploy
            - name: 'Copy the files'
              run: |
                  cp *.tf *.conf LICENSE README.md ./ibm-fortigate-cross-zone-ha-par-terraform-deploy/
            - name: 'Build the ZIP'
              run: |
                  tar -czf ibm-fortigate-cross-zone-ha-par-terraform-deploy.tar.gz ibm-fortigate-cross-zone-ha-par-terraform-deploy/
            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.IBM_TOKEN }}'
                  prerelease: false
                  title: 'ibm-fortigate-cross-zone-ha-par-terraform-deploy ${{github.ref_name}}'
                  files: |
                      ibm-fortigate-cross-zone-ha-par-terraform-deploy.tar.gz